### ISSUE TITLE
No template file for JqGrid

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/views_json#10]
I have to admit, I never used that before, but obviously there's no such template file, hence the Warning:
```
Warning: include(...modules/views_json/views/theme/views-views-json-style-jqgrid.tpl.php): failed to open stream: No such file or directory in include() (line ...core/includes/theme.inc).
```
Odd thing: that file also doesn't exist in the [Drupal module variant](https://git.drupalcode.org/project/views_datasource). <s>Maybe</s> that's also broken in Drupal?

**Comment by indigoxela** [comment]
This is odd...

The D7 version has the same problem - errors because of missing template file. And following the whole git history, it seems like it never existed. The whole jqGrid functionality probably never worked.

The question is now: how to handle that?

**Comment by indigoxela** [comment]
There's an additional [module]( https://www.drupal.org/project/jqgrid) for D7 for JqGrid, which only reports 69 installs.

It seems to me that this functionality isn't the most wanted out there. Also: there's no bug report in the views_datasource queue regarding that broken functionality (throws the same errors in D7), so nobody seems to use it, anyway.

I'm leaning towards "rip the rest out and forget about it".

@jenlampton what do you think?

**Comment by indigoxela** [comment]
Maybe this does work, if we use the "simple" template file. At least, there are no more warnings and the output seems plausible.

**Comment by jenlampton** [comment]
I think it's probably fine to remove the code if you prefer, but if switching the template fixes it, maybe do that and leave it like that?

**Comment by indigoxela** [comment]
> if switching the template fixes it, maybe do that and leave it like that?

After thinking it over, I'm now leaning towards that. I didn't actually test the jQgrid functionality, only compared the outcoming structure with the json from their demo. In theory it works. If it does in practice ... someone will tell us one day. :grin:

It's at least better than with the D7 variant, which only throws warnings and outputs nothing.
