### ISSUE TITLE
There was an error accessing the API SyntaxError:

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/views_json#14]
I'm attempting to get json output and import to make a decoupled block and I get an error in the console.

When I preview the json inside the view it looks fine.

![image](https://user-images.githubusercontent.com/41843284/212109875-4a439371-e537-4e19-8589-78d27bd7c2f5.png)

However when I then view the page the json is not closed.

![image](https://user-images.githubusercontent.com/41843284/212110022-a515db0b-2c4c-4473-a7fa-384a2248a9c2.png)

I get the same thing in Postman.

![image](https://user-images.githubusercontent.com/41843284/212110179-3201dd59-502e-43f2-9d91-b0c06ab6c472.png)

Is this user error on my part or is there a problem with the output?

**Comment by indigoxela** [comment]
> Is this user error on my part or is there a problem with the output?

It's an undesired result. :wink:

From current info it's impossible to guess, what happens. Can you provide steps to reproduce, please?

**Comment by keiserjb** [comment]
I tried to reproduce with a demo site from Backdropcms.org and it worked correctly with posts.  I am seeing correct json in Postman. So things are pointing towards user error.

**Comment by keiserjb** [comment]
Still getting the error on a site with real content though.  I created a display for posts that only shows the title and kept all of the default settings.  The end of the json output gets chopped off.

**Comment by indigoxela** [comment]
Very strange. Even more, as the views preview seems to work in your dev environment.

Can you describe your environment? PHP version, web server, ...
What have you tried so far to debug?

**Comment by keiserjb** [comment]
I first encountered the problem with my local Lando running php 7.4.  I then tried it on my dev branch running in AWS.  Same php 7.4 and had the same problem.  I got the Headless module to work for me instead of this module.

**Comment by indigoxela** [comment]
Whatever works for you. :smiley: With the information I have and no steps to reproduce, I was running out of ideas, anyway.

Feel free to reopen, as soon as you have a clue, what went wrong.
