### ISSUE TITLE
PHP compatibility check causes false result with 8.x

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/views_json#15]
Here's the code: https://github.com/backdrop-contrib/views_json/blob/1.x-1.x/views_json.module#L525

So, with php 8.0 or 8.1 the major version is bigger than 5 AND the minor version is smaller than 3.

This leads to wrong version assumption with 8.x. (Probably also with 7.1 or 7.2)

This popped up in an otherwise unrelated issue in another module https://github.com/backdrop-contrib/resource_timeslots/issues/23

Time to update this ancient code, which currently breaks the "Numeric strings" setting. :smirk:

**Comment by indigoxela** [comment]
I think, we can just drop these workarounds for php 5.2 and 5.4. Backdrop requires at least 5.6 - and that version properly handles json_encode().

**Comment by indigoxela** [comment]
FTR: @olafgrabienski successfully tested this PR (confirmed in the chat).

**Comment by olafgrabienski** [comment]
> FTR: @olafgrabienski successfully tested this PR (confirmed in the chat).

Yep, I've tested it repeating the steps of the related [Resources Timeslots issue report](https://github.com/backdrop-contrib/resource_timeslots/issues/23), and the PR fixed the issue for me.
